# Generated by Django 4.1.7 on 2023-03-25 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_agregue_modelo_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
